# Generated by Django 3.2.8 on 2021-12-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0012_auto_20211218_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail_slot',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
