# Generated by Django 3.2.8 on 2021-12-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0013_avail_slot_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avail_slot',
            name='date',
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('slots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoviSafe.avail_slot')),
            ],
        ),
    ]
